FROM node:20-alpine AS builder
RUN npm install -g pnpm@9 --quiet
WORKDIR /app
ENV NODE_ENV=development
COPY . .
RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @serviceconnect/api run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/apps/api/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
EXPOSE 3001
CMD ["node", "dist/main"]
